Build netcdf4 for arches running older versions
AnacondaRecipes/netcdf4-feedstock pull request #4
Opened 2021-12-17 08:22 UTC by tobijk

--------------------------------------------------------------------
# linux-64
--------------------------------------------------------------------
* netcdf4                        1.5.7  py36h0a24e14_0  pkgs/main
* netcdf4                        1.5.7  py37h0a24e14_0  pkgs/main
* netcdf4                        1.5.7  py38h0a24e14_0  pkgs/main
* netcdf4                        1.5.7  py39h0a24e14_0  pkgs/main
* netcdf4                        1.5.7  py39he70f4c8_0  pkgs/main

--------------------------------------------------------------------
# linux-ppc64le
--------------------------------------------------------------------
* netcdf4                        1.5.7  py36h4785779_0  pkgs/main
* netcdf4                        1.5.7  py37h4785779_0  pkgs/main
* netcdf4                        1.5.7  py38h4785779_0  pkgs/main
* netcdf4                        1.5.7  py39h353ab3d_0  pkgs/main
* netcdf4                        1.5.7  py39h4785779_0  pkgs/main

--------------------------------------------------------------------
# linux-aarch64
--------------------------------------------------------------------
* netcdf4                        1.5.6  py37hdd8981e_0  pkgs/main
* netcdf4                        1.5.6  py38hdd8981e_0  pkgs/main
* netcdf4                        1.5.6  py39hdd8981e_0  pkgs/main

--------------------------------------------------------------------
# linux-s390x
--------------------------------------------------------------------
->Package "netcdf4=1.5" not found!

--------------------------------------------------------------------
# osx-64
--------------------------------------------------------------------
* netcdf4                        1.5.7  py36h1695cb1_0  pkgs/main
* netcdf4                        1.5.7  py37h1695cb1_0  pkgs/main
* netcdf4                        1.5.7  py38h1695cb1_0  pkgs/main
* netcdf4                        1.5.7  py39h1695cb1_0  pkgs/main
* netcdf4                        1.5.7  py39h93ad9c5_0  pkgs/main

--------------------------------------------------------------------
# osx-arm64
--------------------------------------------------------------------
* netcdf4                        1.5.7  py38h42109b7_0  pkgs/main
* netcdf4                        1.5.7  py39h42109b7_0  pkgs/main

--------------------------------------------------------------------
# win-32
--------------------------------------------------------------------
* netcdf4                        1.5.7  py36h618db37_0  pkgs/main
* netcdf4                        1.5.7  py37h618db37_0  pkgs/main
* netcdf4                        1.5.7  py38h618db37_0  pkgs/main
* netcdf4                        1.5.7  py39h618db37_0  pkgs/main
* netcdf4                        1.5.7  py39h7cf66cd_0  pkgs/main

--------------------------------------------------------------------
# win-64
--------------------------------------------------------------------
* netcdf4                        1.5.7  py36hb33177a_0  pkgs/main
* netcdf4                        1.5.7  py37hb33177a_0  pkgs/main
* netcdf4                        1.5.7  py38hb33177a_0  pkgs/main
* netcdf4                        1.5.7  py39hb33177a_0  pkgs/main
* netcdf4                        1.5.7  py39hb76ebac_0  pkgs/main

2022-01-25 16:00 UTC, katietz approved these changes

2022-01-25 17:38 UTC, ScottBailey requested changes
`recipe/run_test.py` should be reverted and line 15 updated to the following:
```
url = 'https://geoport.whoi.edu/thredds/catalog/usgs/vault0/models/vdatum/catalog.html?dataset=usgs/vault0/models/vdatum/gom_vdatum.nc'
```

2022-01-26 15:16 UTC, ScottBailey approved these changes

2022-01-26 19:42 UTC, ScottBailey approved these changes

2022-01-27 19:25 UTC, merged